### ISSUE TITLE
no variables pushed when using -var-file

### ISSUE THREAD

**Issue by jeremygaither** [hashicorp-community/tf-helper#12]
debug logs:
```
[DEBUG] Unable to retrieve value for potential variable aws_account_id
[DEBUG] Stdout of terraform console was:
[DEBUG] 
2019/08/19 16:00:31 [INFO] Terraform version: 0.11.14  
2019/08/19 16:00:31 [INFO] Go runtime version: go1.12.4
2019/08/19 16:00:31 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/1.0.1/versions/0.11.14/terraform", "console", "1"}
2019/08/19 16:00:31 [DEBUG] Attempting to open CLI config file: /Users/jeremy.gaither/.terraformrc
2019/08/19 16:00:31 Loading CLI configuration from /Users/jeremy.gaither/.terraformrc
2019/08/19 16:00:31 [INFO] CLI command args: []string{"console", "1"}
2019/08/19 16:00:31 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: open 1: no such file or directory
```

**Comment by sumitmaggo** [comment]
@fprimex, @jeremygaither  Is there any plan for fixing the pending issues like this one? I have also observed this issue on the latest release. I see that the last commit on this repository happened on Jun 11, is there any further development/support happening on this repo?

**Comment by jeremygaither** [comment]
@sumitmaggo I resorted to using the overly verbose [TFE Provider](https://www.terraform.io/docs/providers/tfe/index.html) instead, since this issue is unresolved.

**Comment by fprimex** [comment]
Hi all, development has been slow because of my having to be pulled into other things. I'm planning to resolve all of these issues as soon as I can.

**Comment by sumitmaggo** [comment]
Thanks @jeremygaither and @fprimex for the responses. 
@fprimex I have encountered couple of other issues in addition to this one, should I create a separate ticket for the same? 
So far, I have tried to fix these issues by manually changing the file after cloning the repo but need those changes in the 'release' branch of this repo so that I can pull and use it in automation.
But I am not sure if the fixes are correct, so can I try making these changes myself and get it reviewed or suggest those changes in the ticket and have you look at it?

**Comment by jeremygaither** [comment]
If you have a fork and potential fixes, I'd recommend opening a PR for folks to test and review. I don't have merge permissions on this repo, but I'll happily test and comment.

**Comment by sumitmaggo** [comment]
Thanks @jeremygaither @fprimex 
I have created a pull request with the necessary changes as per my testing.
https://github.com/hashicorp-community/tf-helper/pull/20
Please review and let me know how the testing goes.

**Comment by sumitmaggo** [comment]
@jeremygaither Did you get a chance to look at the changes and test it?

**Comment by fprimex** [comment]
I merged the associated PR into master, so this will be fixed in the next release.
