### ISSUE TITLE
Option to disable SSL Validation

### ISSUE THREAD

**Issue by mzarglis** [hashicorp-community/tf-helper#16]
Is there a switch we can set to disable SSL validation, if the SSL cert on terraform enterprise is not valid (self-signed) any requests from tf-helper will return HTTP status code 000?

**Comment by fprimex** [comment]
This is possible now by editing the `~/.tfh/curlrc` file. You can add any `curl` command line option into this file to control the connection to TFE, including the `-k/--insecure` option.

**Comment by mzarglis** [comment]
Thanks so much!
