### ISSUE TITLE
update workspace to configure the vcs repo getting "765: unexpected token"

### ISSUE THREAD

**Issue by jennihan** [hashicorp-community/tf-helper#17]
Tried to run the command "tfh workspace update -name fabric2  -vcs-id test/fabric -oauth-id "ot-QAn654UeHQocidjs" to configure the vcs for the workspace, getting below error:

[ERROR] API request failed.
HTTP status code: 400
JSON-API details:
  detail: 765: unexpected token at '{  "data": {    "attributes": {       "vcs-repo" { "identifier": "test/fabric", "oauth-token-id": "ot-QAn654UeHQocidjs"}    },    "type": "workspaces"  }}'
  status: 400
  title: JSON body is invalid

**Comment by fprimex** [comment]
Hi,

This line:

https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/cmd/tfh_workspace_update.sh#L111

Should have a `:` I think. So:

```
    attr_obj="$attr_obj \"vcs-repo\": {$vcs_obj}"
```

Would you be able to make this change and see if it works for you?

**Comment by jennihan** [comment]
Thanks, it works.
