### ISSUE TITLE
Can we trigger/start a run with tfh? 

### ISSUE THREAD

**Issue by mechastorm** [hashicorp-community/tf-helper#18]
I can see options to list, cancel and discard a run. But I do not need an option to start/trigger a run. Am I missing something in the docs or is this a feature that should be added in future iterations?

**Comment by fprimex** [comment]
Are you looking for `tfh pushconfig`? That creates a run with a configuration, or with the current configuration (`-current-config`), or a destroy run. It's pretty overloaded at this point. I'd be surprised if it doesn't have an option for what you're looking for, but let me know.

**Comment by drobakowski** [comment]
Hi @mechastorm I think I ran into the same problem as you. I think you're looking to run a remote execution run on the **free** plan of Terraform Cloud? If so, please see my [comment](https://github.com/hashicorp-community/tf-helper/issues/19#issuecomment-533861472), maybe my custom plugin will help you.

**Comment by fprimex** [comment]
An `fi` wasn't moved far enough down. I think `master` should have the fix now.
