### ISSUE TITLE
pushconfig: HTTP status code 404

### ISSUE THREAD

**Issue by drobakowski** [hashicorp-community/tf-helper#19]
Hi there,

we are trying to queue a new plan for our workspace but do get a 404 HTTP error:

```sh
> tfh pushconfig -org <org_name> -name <workspace_name> -message 'Queue Plan' -current-config true
[ERROR] API request failed.
HTTP status code: 404
JSON-API details:
  status: 404
  title: not found
```

Are we doing something wrong or could this be a problem with terraform current API? The workspace is configured for remote runs and terraform run uses version `0.12.9`.

**Comment by drobakowski** [comment]
I've noticed that `pushconfig` runs against a different enterprise API than I was expecting. I was trying to queue a plan for a remote execution for the Terraform Cloud non enterprise version, which was released earlier this month. Any idea on how to work with both Terraform Cloud endpoints?

In the meantime, I've created a docker image with a custom plugin for my needs, maybe my plugin can help others to accomplish there needs. See https://github.com/synlay/docker-tf-helper and [tfh_queueplan](https://github.com/synlay/docker-tf-helper/blob/master/tfh_plugins/queueplan/tfh_queueplan.md)

**Comment by fprimex** [comment]
Hi, Terraform Cloud is what Terraform Enterprise (the hosted, SaaS TFE) was. It was just a renaming. So the API should be the same still. The `pushconfig` command uses numerous calls into TFC / TFE and is pretty complicated, so more information would be needed to get to the bottom of your troubles.

**Comment by fprimex** [comment]
I am just getting back into tfh development after a long layoff, so I'll add this to the heap and see what I can find.

**Comment by fprimex** [comment]
Also, I am SUPER happy you were able to do a plugin that solved your problem :) :)

**Comment by fprimex** [comment]
An `fi` wasn't moved far enough down. I think `master` should have the fix now.
