### ISSUE TITLE
pushconfig: Error 404 with -destroy

### ISSUE THREAD

**Issue by abdennebi** [hashicorp-community/tf-helper#21]
Hi,

When adding the ``-destroy`` parameter, I get an 404 error because the script is calling the ``https://app.terraform.io/api/v2/configuration-versions/``endpoint without configuration_id.

When destroy is activated the variable ``$config_id``is null at this line: https://github.com/hashicorp-community/tf-helper/blob/0fba4dcce876bb5d4ff6a17cda5f56e8ddf36007/tfh/lib/tfh/cmd/tfh_pushconfig.sh#L327

**Comment by fprimex** [comment]
I think I have resolved this. There was a `fi` that was not where it should have been in `pushconfig` that was causing many errors.

**Comment by fprimex** [comment]
Fix is in `master`. Will be in the next release.
