### ISSUE TITLE
-destroy on pushconfig not tearing down resources

### ISSUE THREAD

**Issue by TylerPinson** [hashicorp-community/tf-helper#26]
i have started using the tf-helper to help provision and tear down testing environments. i have found however when running pushconfig with -destroy, it queues a plan but does not tear down resources. 
my tfh version is based on the master branch at commit sha: 746c31b096f95941e0de6a475fe784a98a2013f4
which is the current head. im using this instead of release due to some logic needed for exiting the polling status properly. 

i believe the issue regarding the destroy is rooted from the make_run_payload call passing in a '1' if -destroy is set vs a "true"
https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/cmd/tfh_pushconfig.sh#L345
based on the request-body api docs a boolean is required but im not sure a '1' here satisfies that constraint. 
https://www.terraform.io/docs/cloud/api/run.html#request-body

i have an easy workaround involving applying a patch to the code that works and properly deletes the resources where i simply pass a true/false into the make_run_payload call. here is that code diff
```
-  make_run_payload "$destroy" "$message" "$config_id" "$workspace_id"
+  if [ $destroy ]; then
+      destroy_bool="true"
+  else
+      destroy_bool="false"
+  fi
+
+  make_run_payload "$destroy_bool" "$message" "$config_id" "$workspace_id"
```

this is the original payload that gets sent (with -destroy and without the above changes):
```
{
"data": {
  "attributes": {   
    "is-destroy": 1,
    "message": "destroy-test"
  },
  "type":"runs",
  "relationships": {
    "workspace": {
    "data": {
      "type": "workspaces",
      "id": "ws-xxxxx"
    }
    }
  }
}
}
```
and here is the payload with the above changes (and -destroy):
```
{
"data": {
  "attributes": {
    "is-destroy": true,
    "message": "destroy-test"
  },
  "type":"runs",
  "relationships": {
    "workspace": {
    "data": {
      "type": "workspaces",
      "id": "ws-xxx"
    }
    }
  }
}
}
```

is it possible that i am missing a parameter or setting somewhere which would require me to not have to patch the code?

**Comment by fprimex** [comment]
Thanks for the bug report. This bit of code didn't get updated when I made bools able to be flags (`-destroy`) instead of requiring a true/false argument (`-destroy true`). When that happened the value of `destroy` went from being either `true` or `false` to set (normalized to `1`) or the null value.

Your patch is exactly what's needed. If you want to PR it to the master branch I will get it merged. I need to cut a new release soon also.

**Comment by fprimex** [comment]
I would say go ahead and remove the default from this line as well, since it will either be `true` or `false` by that point:

https://github.com/hashicorp-community/tf-helper/blob/master/tfh/lib/tfh/cmd/tfh_pushconfig.sh#L144

So it's just

```
    "is-destroy": $1,
```

**Comment by TylerPinson** [comment]
i would have made a branch/PR for you but i do not appear to have access rights.

**Comment by fprimex** [comment]
Please create a fork and send the PR from that

**Comment by TylerPinson** [comment]
there ya go:
https://github.com/hashicorp-community/tf-helper/pull/27

**Comment by fprimex** [comment]
Thanks! It's in master and hopefully I will magically acquire some time to do a new release :)
