### ISSUE TITLE
Issue with TF token

### ISSUE THREAD

**Issue by skommuri12** [hashicorp-community/tf-helper#28]
After exporting orgname, hostname, token, I am not to find Workspaces.
When I try
$ tfh workspace list
[ERROR] Unable to complete API request.
[ERROR] HTTP status code: 000.
[ERROR] Response:
[ERROR]
[ERROR] Error listing workspaces for....

**Comment by fprimex** [comment]
You can `export TF_LOG=1` (or any value) to obtain a very detailed log. I think that is likely to show the reason for the error. You may not want to post that log here, as it might contain sensitive information, but please look over it to see what it shows. If that doesn't turn anything up we can go from there.
