### ISSUE TITLE
How i can upload credentials file as tf cloud var

### ISSUE THREAD

**Issue by gogovan-vincentngai** [hashicorp-community/tf-helper#29]
Hi 

I success install and using tfh to push some var to tf cloud 
When need create GCP object and use GCP Service Account i will have service account and the json file.

I did try expose by 
export TF_VAR_credentials=$(cat cred.json)
export TF_VAR_credentials=cred.json
export TF_VAR_credentials=$(<cred.json)
TF_VAR_credentials=cred.json

either it directly use cred.json as value 
or 
tfh appear error
```
>  tfh pushvars -svar cred=$TF_VAR_credentials
[ERROR] all positional parameters must precede all options
```

**Comment by fprimex** [comment]
I think you just need to quote the variable as it probably has some spaces and line endings in it. Use the first `export` command that you have there, and `echo "$TF_VAR_credentials` to ensure it contains what you think it should (the file _contents_). The quotes on the `echo` are important too.

```
>  tfh pushvars -svar cred="$TF_VAR_credentials"
```

I'll close this but I think you can reopen if you ned to. Cheers!
