### ISSUE TITLE
tfh command produces junonia syntax error

### ISSUE THREAD

**Issue by scarolan** [hashicorp-community/tf-helper#3]
```
/home/scarolan/bin/tfh: 2683: /home/scarolan/git_repos/tf-helper/tfh/lib/tfh/junonia: Syntax error: Missing '))'
```

This happens on Debian 9 under either bash or zsh.

**Comment by scarolan** [comment]
Here's the debug output
```
bash -x tfh
+ readonly 'TFH_CMDLINE=tfh '
+ TFH_CMDLINE='tfh '
+ '[' -n '' ']'
+ tar_verbose=
+ curl_silent=-s
+ exec
+ junonia_bootstrap
+ JUNONIA_TARGET=tfh
+ '[' -h tfh ']'
+++ dirname tfh
++ cd .
++ pwd -P
+ JUNONIA_PATH=/home/scarolan/git_repos/tf-helper/tfh/lib/tfh
++ basename tfh
+ JUNONIA_TARGET=/home/scarolan/git_repos/tf-helper/tfh/lib/tfh/tfh
++ basename /home/scarolan/git_repos/tf-helper/tfh/lib/tfh
+ '[' tfh = bin ']'
+ . /home/scarolan/git_repos/tf-helper/tfh/lib/tfh/lib/tfh/junonia
/home/scarolan/bin/tfh: line 408: /home/scarolan/git_repos/tf-helper/tfh/lib/tfh/lib/tfh/junonia: No such file or directory
+ echodebug /home/scarolan/git_repos/tf-helper/tfh/lib/tfh
/home/scarolan/bin/tfh: line 410: echodebug: command not found
+ echodebug 'tfh '
/home/scarolan/bin/tfh: line 411: echodebug: command not found
+ junonia_run
/home/scarolan/bin/tfh: line 413: junonia_run: command not found
+ exit 127
```

**Comment by fprimex** [comment]
Seems like some versions of `dash` believe that this line:

https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/junonia#L1394

has an arithmetic expansion, `$((`, even though there is no `))`. This syntax is valid in a number of other shells, one of which being a later version of `dash` than appears to come with the Debian Docker container. It fails for me (reproducing your issue), with Debian 9.9 and `dash` 0.5.8-2.4. It does not fail for me on MacOS with `dash` 0.5.10.2 from Homebrew (or any other shell I test with).

Well, appears to be a bug in `dash` that has already been fixed, but I can add a _single_ space to fix the issue for this particular broken version.

In the meantime you can work around this by running the program with `bash` on Debian.

**Comment by fprimex** [comment]
> This happens on Debian 9 under either bash or zsh.

> you can work around this by running the program with bash on Debian.

To clarify on this, whether using `bash` or `zsh` the shell used is `/bin/sh` (`dash`) when executing `tfh` directly (`./tfh` or `tfh` if in the path). On Debian 9, /bin/sh is dash. To work around the problem you need to instead run the program as `bash path/to/tfh`, which will execute `tfh` using `bash` instead. You could perhaps do something like `alias tfh="bash tfh"`, but I'll have this fixed likely tomorrow.

**Comment by fprimex** [comment]
I worked on this shortly after it was reported to diagnose the problem and saw some other related things that might need to be fixed. I had to travel and work on other things over the past week, so this fix has not happened yet. I'm picking this and the other things up now.

**Comment by fprimex** [comment]
Still continuing to find and fix things on the Ubuntu container. Found another problem with their `mawk` (which is ~20 years old now). Brew has the unofficial 1.3.4 fork, so I missed this.

I am going to put up a huge h1 sized message on the junonia git asking the Debian/Ubuntu maintainers to make gawk the default awk. It's more than a little weird that GNU/Linux doesn't use the GNU AWK.

Everyone needs to stop using it, and Mike needs to finish his 2.0, which was in "beta" 3 years ago.

**Comment by fprimex** [comment]
OK, I think I got everything. Version 0.2.6 is in the default `release` branch now. Please let me know if you find any other issues. Thanks!
