### ISSUE TITLE
import resources into remote state

### ISSUE THREAD

**Issue by aidan-melen** [hashicorp-community/tf-helper#30]
It would be great if this CLI tool could help with importing resources into a remote state.

If you have a TFE workspace configured with VSC, then you can't have a backend configured. They are mutually exclusive. So to import state, you need to configure the workspace for "No VCS", setup backend, import resource into remote state, and reconfigure the workspace to have VCS again.

**Comment by fprimex** [comment]
You can put a remote backend in the configuration, init, the do the imports regardless as to the VCS settings as far as I know. TFC/TFE overrides any backend configuration and sets it to the workspace's state storage.

**Comment by aidan-melen** [comment]
Yeah, but a remote TFE backend and  TFE workspace integrated with VCS are mutually exclusive configurations.

**Comment by fprimex** [comment]
With a VCS backed workspace you can't apply but you can import. I'm not at the desk at the moment to confirm but this should be possible. `terraform state mv` also should work. The token being used has to have write permission on the workspace.

**Comment by aidan-melen** [comment]
Okay, I stand corrected. you can configure the remote backend with the VCS integrated workspace.
