### ISSUE TITLE
random_enough function is missing

### ISSUE THREAD

**Issue by gregglowrimore** [hashicorp-community/tf-helper#5]
I pulled the latest version of this repo and immediately began running a 'tfh pushvars' command and was greeted with:

"/Users/glowrimore/Development/tf-helper/tfh/lib/tfh/cmd/tfh_pushvars.sh: line 458: random_enough: command not found"

**Comment by fprimex** [comment]
Should be fixed by 0.2.6. Just pull the default `release` branch!
