### ISSUE TITLE
hostname is not working if set from the ~/.tfh/tfhrc

### ISSUE THREAD

**Issue by samm-git** [hashicorp-community/tf-helper#6]
I found that if i am setting hostname in the`~/.tfh/tfhrc` it is not working as intended:

```
TFH_hostname="example.com"
```

`./tfh/bin/tfh workspace list -org test` will give a curl call to the `https://app.terraform.ioexample.com/api/v2/organizations/test/workspaces` However, if i am setting it using `-hostname` it is working as intended.

**Comment by fprimex** [comment]
This was an error whereby options with defaults that also had values in the config file were appending the config file values rather than overwriting them. Fix in 0.2.7, just released. Thanks for the continued reports!
