### ISSUE TITLE
Can't run on linux box

### ISSUE THREAD

**Issue by estein9825** [hashicorp-community/tf-helper#8]
When attempt to run the tfh program on 
`Linux x86_64 x86_64 x86_64 GNU/Linux`

I get this error:
```
$ ./tfh
awk: cmd. line:275: fatal: Invalid range end: /^## `[,-_A-Za-z0-9 ]+`/
[ERROR] Unable to generate spec from source provided: /home/ec2-user/tf-helper/tfh/usr/share/doc/tfh
[ERROR] Source should be a directory of Markdown, a Markdown file,
[ERROR] or a shell string variable containing the Markdown contents.
```

**Comment by fprimex** [comment]
Hi, I’ll be able to look at this some time next week. My guess is that the `,-_` is being interpreted as a range. What awk are you using, out of curiosity?

You could try changing that to `-,_`, which will be my first try next week. Cheers.

**Comment by fprimex** [comment]
Hi @estein9825 , could you let me know which `awk` you are using?

**Comment by estein9825** [comment]
Sorry, I never received an email notification regarding your response.  Here you go:
```
$ awk -W version
GNU Awk 3.1.7
Copyright (C) 1989, 1991-2009 Free Software Foundation.
```

**Comment by sanchojaf** [comment]
Same issue for me

```
$ awk -W version
GNU Awk 3.1.7
```

**Comment by fprimex** [comment]
Should be resolved with the above commit to master ☝️ . It'll be in the next release. If you get a chance please give it a try.
