### ISSUE TITLE
OSX: Unable to retrieve value for potential variable myvariable with pushvars

### ISSUE THREAD

**Issue by jvanan24** [hashicorp-community/tf-helper#9]
Cannot use "pushvars" (pullvars is ok and -var myvariable="xxx" too) on OSX 10.14.5 / tfh 0.2.7 when using a tfvars file.

Content of test_vars.tfvars :
`
myvariable = "test"
`

here is the debug log :

bash-3.2$ tfh pushvars -org TRAINING -name test_token_vault -var-file test_vars.tfvars
[DEBUG] begin init
[DEBUG] /Users/user1/Documents/terraform/examples/
[DEBUG] /Users/user1/bin/tfh pushvars -org TRAINING -name test_token_vault -var-file test_vars.tfvars
[DEBUG] begin run
[DEBUG] begin runmd filtered
[DEBUG] begin run final
[DEBUG] begin set args
[DEBUG] begin exec
[DEBUG] begin normalize func
org:       TRAINING
prefix:
workspace: test_token_vault
hostname:  terraform.somecompany.org
address:   https://terraform.somecompany.org
verbose:   1
vverbose:  1
vvverbose: 1
[DEBUG] token from env and config file
token:     not empty
curlrc:    /Users/user1/.tfh/curlrc, unused
[DEBUG] Shifting 9 arguments
[DEBUG] begin func search
[DEBUG] JUNONIA_CMD      : tfh pushvars
[DEBUG] JUNONIA_FUNC     : tfh_pushvars
[DEBUG] JUNONIA_SPEC_TYPE: cached_dir
[DEBUG] args:              test_vars.tfvars 1
2019/08/06 10:51:27 [WARN] Invalid log level: "1". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
2019/08/06 10:51:27 [INFO] Terraform version: 0.11.13
2019/08/06 10:51:27 [INFO] Go runtime version: go1.11.5
2019/08/06 10:51:27 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/0.6.0/versions/0.11.13/terraform", "-version"}
2019/08/06 10:51:27 [DEBUG] Attempting to open CLI config file: /Users/user1/.terraformrc
2019/08/06 10:51:27 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/06 10:51:27 [INFO] CLI command args: []string{"version", "-version"}
2019/08/06 10:51:27 [DEBUG] checking for provider in "."
2019/08/06 10:51:27 [DEBUG] checking for provider in "/usr/local/Cellar/tfenv/0.6.0/versions/0.11.13"
2019/08/06 10:51:27 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/08/06 10:51:27 [DEBUG] checking for provider in "/Users/user1/.terraform.d/plugins"
2019/08/06 10:51:28 [DEBUG] plugin: waiting for all plugin processes to complete...
[DEBUG] API list variables URL:
[DEBUG] https://terraform.somecompany.org/api/v2/vars?filter%5Borganization%5D%5Bname%5D=TRAINING&filter%5Bworkspace%5D%5Bname%5D=test_token_vault
[DEBUG] API request for variable list:
[DEBUG] tfh_api_call args: https://terraform.somecompany.org/api/v2/vars?filter%5Borganization%5D%5Bname%5D=TRAINING&filter%5Bworkspace%5D%5Bname%5D=test_token_vault
[DEBUG] npages: 10000
[DEBUG] curl args: https://terraform.somecompany.org/api/v2/vars?filter%5Borganization%5D%5Bname%5D=TRAINING&filter%5Bworkspace%5D%5Bname%5D=test_token_vault
curl --header "Content-Type: application/vnd.api+json"
     --header "Authorization: Bearer $TFH_token"
     https://terraform.somecompany.org/api/v2/vars?filter%5Borganization%5D%5Bname%5D=TRAINING&filter%5Bworkspace%5D%5Bname%5D=test_token_vault
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   415    0   415    0     0    631      0 --:--:-- --:--:-- --:--:--   631
[DEBUG] API request http code: 200. Response:
{"data":[{"id":"var-7mhAdFPpjmq3UyNu","type":"vars","attributes":{"key":"key","value":"toto2","sensitive":false,"category":"terraform","hcl":false,"created-at":"2019-07-24T15:52:17.690Z"},"relationships":{"configurable":{"data":{"id":"ws-1E5uZTUgtLuYkZVz","type":"workspaces"},"links":{"related":"/api/v2/organizations/TRAINING/workspaces/test_token_vault"}}},"links":{"self":"/api/v2/vars/var-7mhAdFPpjmq3UyNu"}}]}
[DEBUG] Temporary tfvars dir:
[DEBUG] /var/folders/jl/9nbdxsq55yq48h_6nq3fn2q80000gp/T/tfe-push-vars-4174826202
[DEBUG] Temporary directory contents:
[DEBUG] test_vars.tfvars
vars.tf
[DEBUG] Temporary file contents:
[DEBUG] myvariable = "test"

variable "myvariable" {}
[DEBUG] All variables:
[DEBUG] myvariable
2019/08/06 10:51:29 [WARN] Invalid log level: "1". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
2019/08/06 10:51:29 [INFO] Terraform version: 0.11.13
2019/08/06 10:51:29 [INFO] Go runtime version: go1.11.5
2019/08/06 10:51:29 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/0.6.0/versions/0.11.13/terraform", "console", "1"}
2019/08/06 10:51:29 [DEBUG] Attempting to open CLI config file: /Users/user1/.terraformrc
2019/08/06 10:51:29 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/06 10:51:29 [INFO] CLI command args: []string{"console", "1"}
2019/08/06 10:51:29 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: open 1: no such file or directory

[DEBUG] Unable to retrieve value for potential variable myvariable
[DEBUG] Stdout of terraform console was:
[DEBUG]

**Comment by mengesb** [comment]
I have this same problem however I'm not using tfenv, and I've tried terraform 0.11.14 and 0.12.5 - both result in the same message

**Comment by fprimex** [comment]
Thanks for the report. On this line:

https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/cmd/tfh_pushvars.sh#L472

I go to the temporary directory and don't go anywhere else later. The `-var-file` argument is relative in this case, so the command that's being run ends up being:

```
(temp dir) $ echo "var.myvariable" | terraform console test_vars.tfvars 2>&3
```

I need to resolve the absolute path to the given variable file. Additionally, I think either this line:

https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/cmd/tfh_pushvars.sh#L252


needs to be

```
    var_file_arg="-var-file $1"
```

or this line:

https://github.com/hashicorp-community/tf-helper/blob/release/tfh/lib/tfh/cmd/tfh_pushvars.sh#L643

needs to be

```
        val_lines="$(echo "var.$var" | terraform console -var-file "$var_file_arg" 2>&3)"
```

**Comment by fprimex** [comment]
I merged the associated PR into master, so I am going to close this as the fix will be in the next release.
